package ec.edu.espe.alertsystem.view;

/**
 *
 * @author JOSUE
 */
public class FrmAlertSystemMenuAssistant extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAlertSystemMenuAssistant.class.getName());

    /**
     * Creates new form FrmAlertSystemMenuAssistant
     */
    public FrmAlertSystemMenuAssistant() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuProfile = new javax.swing.JMenu();
        MnuLogOut = new javax.swing.JMenuItem();
        MnuExit = new javax.swing.JMenuItem();
        MnuSeePerformanceIndicator = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnuSeeTask = new javax.swing.JMenu();
        MnuSeeMyPerformanceIndicatorbtn = new javax.swing.JMenuItem();
        MnuSeeAlerts = new javax.swing.JMenu();
        MnuSeeMyAlertsbtn = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenuItem1.setText("jMenuItem1");

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 185, 255));

        jPanel1.setBackground(new java.awt.Color(200, 185, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Bienvenido Asistente ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(200, 185, 255));

        MnuProfile.setText("Perfil");

        MnuLogOut.setText("Cerrar Sesión");
        MnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuLogOutActionPerformed(evt);
            }
        });
        MnuProfile.add(MnuLogOut);

        MnuExit.setText("Cerrar Programa");
        MnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuExitActionPerformed(evt);
            }
        });
        MnuProfile.add(MnuExit);

        jMenuBar1.add(MnuProfile);

        MnuSeePerformanceIndicator.setText("Rendimiento");

        jMenuItem2.setText("Ver Mis Indicadores de Rendimiento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnuSeePerformanceIndicator.add(jMenuItem2);

        jMenuBar1.add(MnuSeePerformanceIndicator);

        MnuSeeTask.setText("Tareas");

        MnuSeeMyPerformanceIndicatorbtn.setText("Ver mis Tareas");
        MnuSeeMyPerformanceIndicatorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSeeMyPerformanceIndicatorbtnActionPerformed(evt);
            }
        });
        MnuSeeTask.add(MnuSeeMyPerformanceIndicatorbtn);

        jMenuBar1.add(MnuSeeTask);

        MnuSeeAlerts.setText("Alertas");

        MnuSeeMyAlertsbtn.setText("Ver mis Alertas");
        MnuSeeMyAlertsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSeeMyAlertsbtnActionPerformed(evt);
            }
        });
        MnuSeeAlerts.add(MnuSeeMyAlertsbtn);

        jMenuBar1.add(MnuSeeAlerts);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuLogOutActionPerformed
       FrmAlertSystemLogin frmAlertSystemLogin = new FrmAlertSystemLogin();
       frmAlertSystemLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_MnuLogOutActionPerformed

    private void MnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_MnuExitActionPerformed

    private void MnuSeeMyPerformanceIndicatorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSeeMyPerformanceIndicatorbtnActionPerformed
      FrmSeeMyTask frmSeeMyTask = new FrmSeeMyTask();
      frmSeeMyTask.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_MnuSeeMyPerformanceIndicatorbtnActionPerformed

    private void MnuSeeMyAlertsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSeeMyAlertsbtnActionPerformed
        FrmSeeMyAlerts frmSeeMyAlerts = new FrmSeeMyAlerts();
        frmSeeMyAlerts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuSeeMyAlertsbtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmSeeMyPerformanceIndicators frmSeeMyPerformanceIndicators = new FrmSeeMyPerformanceIndicators();
        frmSeeMyPerformanceIndicators.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAlertSystemMenuAssistant().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuExit;
    private javax.swing.JMenuItem MnuLogOut;
    private javax.swing.JMenu MnuProfile;
    private javax.swing.JMenu MnuSeeAlerts;
    private javax.swing.JMenuItem MnuSeeMyAlertsbtn;
    private javax.swing.JMenuItem MnuSeeMyPerformanceIndicatorbtn;
    private javax.swing.JMenu MnuSeePerformanceIndicator;
    private javax.swing.JMenu MnuSeeTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
