package ec.edu.espe.alertsystem.view;

import ec.edu.espe.alertsystem.controller.CustomerController;
import ec.edu.espe.alertsystem.controller.EmailSender;
import ec.edu.espe.alertsystem.controller.InvoiceController;
import ec.edu.espe.alertsystem.controller.InvoicePDFGenerator;
import ec.edu.espe.alertsystem.model.Customer;
import ec.edu.espe.alertsystem.model.Invoice;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Paulo Ramos
 */
public class FrmInvoice extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInvoice.class.getName());

    /**
     * Creates new form FrmInvoice
     */
    public FrmInvoice() {
        initComponents();
        loadInvoicesTable();
        calcularTotalTable();
        updateSumaTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnReturn = new javax.swing.JButton();
        btnCompletePayment = new javax.swing.JButton();
        btnGenerateInvoice = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnuLogOut = new javax.swing.JMenuItem();
        MnuExite = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnuBacktoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 185, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Facturas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(200, 185, 255));

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero de Factura", "Dia de Pago", "Subtotal", "Total", "Detalles", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblInvoice);

        jLabel2.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(200, 185, 255));

        btnReturn.setBackground(new java.awt.Color(165, 215, 255));
        btnReturn.setText("Volver al Menu");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnCompletePayment.setBackground(new java.awt.Color(165, 215, 255));
        btnCompletePayment.setText("Completar Pago");
        btnCompletePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletePaymentActionPerformed(evt);
            }
        });

        btnGenerateInvoice.setText("Generar Factura");
        btnGenerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(btnCompletePayment)
                .addGap(32, 32, 32)
                .addComponent(btnGenerateInvoice)
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnCompletePayment)
                    .addComponent(btnGenerateInvoice))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jMenu1.setText("Perfil");

        MnuLogOut.setText("Cerrar Sesión");
        MnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(MnuLogOut);

        MnuExite.setText("Cerrar Programa");
        MnuExite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuExiteActionPerformed(evt);
            }
        });
        jMenu1.add(MnuExite);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        MnuBacktoMenu.setText("Back to Menu");
        MnuBacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuBacktoMenuActionPerformed(evt);
            }
        });
        jMenu2.add(MnuBacktoMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmAlertSystemMenuBoss menuBoss = new FrmAlertSystemMenuBoss();
        menuBoss.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCompletePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletePaymentActionPerformed
        int selectedRow = tblInvoice.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una factura para completar el pago.");
            return;
        }

        String status = (String) tblInvoice.getValueAt(selectedRow, 5); // Columna Estado
        if ("Pagado".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "La factura ya está pagada.");
            return;
        }

        String inputDate = JOptionPane.showInputDialog(this, "Ingrese fecha de pago (dd/MM/yyyy):");
        if (inputDate == null || inputDate.isEmpty()) {
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date paymentDate = sdf.parse(inputDate);

            int invoiceNumber = (int) tblInvoice.getValueAt(selectedRow, 0);

            InvoiceController.actualizarPagoFactura(invoiceNumber, paymentDate);

            loadInvoicesTable();
            calcularTotalTable();
            updateSumaTotal();

            JOptionPane.showMessageDialog(this, "Pago completado exitosamente.");

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido.");
        }
    }//GEN-LAST:event_btnCompletePaymentActionPerformed

    private void MnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuLogOutActionPerformed
        FrmAlertSystemLogin frmAlertSystemLogin = new FrmAlertSystemLogin();
        frmAlertSystemLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuLogOutActionPerformed

    private void MnuExiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuExiteActionPerformed
        this.dispose();
    }//GEN-LAST:event_MnuExiteActionPerformed

    private void MnuBacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuBacktoMenuActionPerformed
        FrmAlertSystemMenuBoss frmAlertSystemMenuBoss = new FrmAlertSystemMenuBoss();
        frmAlertSystemMenuBoss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuBacktoMenuActionPerformed

    private void btnGenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInvoiceActionPerformed
        int selectedRow = tblInvoice.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una factura");
            return;
        }

        String status = tblInvoice.getValueAt(selectedRow, 5).toString();

        if (!status.equalsIgnoreCase("Pagado")) {
            JOptionPane.showMessageDialog(this,
                    "La factura debe estar pagada");
            return;
        }

        int invoiceNumber = Integer.parseInt(
                tblInvoice.getValueAt(selectedRow, 0).toString()
        );

        Invoice invoice = InvoiceController.getInvoiceByNumber(invoiceNumber);

        if (invoice == null) {
            JOptionPane.showMessageDialog(this, "No se encontró la factura");
            return;
        }

        String clientName = InvoiceController.extractClientName(invoice.getDetails());

        if (clientName == null) {
            JOptionPane.showMessageDialog(this, "No se pudo identificar el cliente");
            return;
        }

        Customer customer = CustomerController.getCustomerByName(clientName);

        if (customer == null) {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado en el sistema");
            return;
        }

        String pdfPath = InvoicePDFGenerator.generate(invoice, customer);

        EmailSender.sendInvoiceByEmail(
                customer.getEmail(),
                customer.getName(),
                pdfPath
        );

        JOptionPane.showMessageDialog(this,
                "Factura generada y enviada al correo del cliente");


    }//GEN-LAST:event_btnGenerateInvoiceActionPerformed

    private void loadInvoicesTable() {

        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
        model.setRowCount(0);

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        for (Document doc : InvoiceController.getInvoices()) {

            int invoiceNumber = doc.getInteger("invoiceNumber", 0);

            String status = doc.getString("status");

            Object paymentObj = doc.get("paymentDate");
            String paymentDate = "";

            if (!"Pendiente".equalsIgnoreCase(status)) {
                if (paymentObj instanceof Date) {
                    paymentDate = dateFormat.format((Date) paymentObj);
                } else if (paymentObj != null) {
                    paymentDate = paymentObj.toString();
                }
            }

            double subtotal = doc.getDouble("amountPaid");
            double total = InvoiceController.calcularTotal(subtotal);

            String details = doc.getString("details");

            model.addRow(new Object[]{
                invoiceNumber,
                paymentDate,
                String.format("%.2f", subtotal),
                String.format("%.2f", total),
                details,
                status
            });
        }
    }

    private void calcularTotalTable() {

        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

            Object subtotalObj = model.getValueAt(i, 2);

            if (subtotalObj != null) {
                String subtotalStr = subtotalObj.toString().replace(",", ".");

                try {
                    double subtotal = Double.parseDouble(subtotalStr);
                    double total = InvoiceController.calcularTotal(subtotal);

                    model.setValueAt(
                            String.format("%.2f", total),
                            i,
                            3
                    );
                } catch (NumberFormatException e) {
                    System.err.println("Error parseando subtotal en fila " + i + ": " + subtotalObj);
                }
            }
        }
    }

    private void updateSumaTotal() {
        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
        double suma = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            Object totalObj = model.getValueAt(i, 3);

            if (totalObj != null) {
                String totalStr = totalObj.toString().replace(",", ".");
                try {
                    double total = Double.parseDouble(totalStr);
                    suma += total;
                } catch (NumberFormatException e) {
                    System.err.println("Error parseando total en fila " + i + ": " + totalObj);
                }
            }
        }

        jLabel3.setText(String.format("%.2f", suma));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInvoice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuBacktoMenu;
    private javax.swing.JMenuItem MnuExite;
    private javax.swing.JMenuItem MnuLogOut;
    private javax.swing.JButton btnCompletePayment;
    private javax.swing.JButton btnGenerateInvoice;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInvoice;
    // End of variables declaration//GEN-END:variables
}
