package ec.edu.espe.alertsystem.view;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import ec.edu.espe.alertsystem.controller.MongoConnection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import java.lang.String;
import java.util.Locale;

/**
 *
 * @author JOSUE
 */
public class FrmSeeMyAlerts extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSeeMyAlerts.class.getName());

    /**
     * Creates new form FrmSeeMyAlerts
     */
    public FrmSeeMyAlerts() {
        initComponents();
        loadAssistantTasks();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssistantTask = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnReturn = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        MnuProfile = new javax.swing.JMenu();
        MnuLogOut = new javax.swing.JMenuItem();
        MnuExite = new javax.swing.JMenuItem();
        MnuMenu = new javax.swing.JMenu();
        MnuBactToMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 185, 255));

        jPanel1.setBackground(new java.awt.Color(200, 185, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ver mis Alertas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(200, 185, 255));

        tblAssistantTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero de Tarea", "Nombre ", "Cliente", "Estado", "Fecha de Entrega", "Dias Restantes"
            }
        ));
        jScrollPane1.setViewportView(tblAssistantTask);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(200, 185, 255));

        btnReturn.setBackground(new java.awt.Color(165, 215, 255));
        btnReturn.setText("Volver al Menu");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnReturn)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addGap(30, 30, 30))
        );

        MnuProfile.setText("Perfil");

        MnuLogOut.setText("Cerrar Sesion");
        MnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuLogOutActionPerformed(evt);
            }
        });
        MnuProfile.add(MnuLogOut);

        MnuExite.setText("Cerrar Programa");
        MnuExite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuExiteActionPerformed(evt);
            }
        });
        MnuProfile.add(MnuExite);

        jMenuBar3.add(MnuProfile);

        MnuMenu.setText("Menu");

        MnuBactToMenu.setText("Volver al Menu");
        MnuBactToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuBactToMenuActionPerformed(evt);
            }
        });
        MnuMenu.add(MnuBactToMenu);

        jMenuBar3.add(MnuMenu);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmAlertSystemMenuAssistant frmAlertSystemMenuAssistant = new FrmAlertSystemMenuAssistant();
        frmAlertSystemMenuAssistant.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void MnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuLogOutActionPerformed
        FrmAlertSystemLogin frmAlertSystemLogin = new FrmAlertSystemLogin();
        frmAlertSystemLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuLogOutActionPerformed

    private void MnuExiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuExiteActionPerformed
        this.dispose();
    }//GEN-LAST:event_MnuExiteActionPerformed

    private void MnuBactToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuBactToMenuActionPerformed
        FrmAlertSystemMenuAssistant frmAlertSystemMenuAssistant = new FrmAlertSystemMenuAssistant();
        frmAlertSystemMenuAssistant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuBactToMenuActionPerformed

    private void loadAssistantTasks() {

    DefaultTableModel model = (DefaultTableModel) tblAssistantTask.getModel();
    model.setRowCount(0);

    MongoCollection<Document> taskCollection =
            MongoConnection.getConnection().getCollection("tasks");

    FindIterable<Document> tasks = taskCollection.find(Filters.eq("assignedTo", "Paulo Ramos"));

    for (Document doc : tasks) {

        int id = doc.getInteger("id");
        String description = doc.getString("description");
        String client = doc.getString("customer");
        String status = doc.getString("status");

        String dateString = "";
        int daysRemaining = 0;
        Object dateObj = doc.get("deliveryDate");

        Date deliveryDate = null;

        try {
            if (dateObj instanceof Date) {
                deliveryDate = (Date) dateObj;
            } else if (dateObj instanceof String) {
                SimpleDateFormat parser =
                        new SimpleDateFormat("MMM dd, yyyy, hh:mm:ss a", Locale.ENGLISH);
                deliveryDate = parser.parse(dateObj.toString());
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
            dateString = sdf.format(deliveryDate);

            Date today = new Date();
            long diffMillis = deliveryDate.getTime() - today.getTime();
            daysRemaining = (int) (diffMillis / (1000 * 60 * 60 * 24));

        } catch (Exception e) {
            dateString = dateObj != null ? dateObj.toString() : "";
            daysRemaining = 0;
        }

        model.addRow(new Object[]{
                id,
                description,
                client,
                status,
                dateString,
                daysRemaining
        });
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSeeMyAlerts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuBactToMenu;
    private javax.swing.JMenuItem MnuExite;
    private javax.swing.JMenuItem MnuLogOut;
    private javax.swing.JMenu MnuMenu;
    private javax.swing.JMenu MnuProfile;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAssistantTask;
    // End of variables declaration//GEN-END:variables
}
